### ISSUE TITLE
Evaluation results are always 0% success rates.

### ISSUE THREAD

**Issue by jasonseu** [facebookresearch/r3m#16]
Hi, thanks for your great work. I have configured all the environment depended by Franka Kitchen and Adroit about a month ago, and training results, and the training results look similar to the paper. However, recently I reconfigured the environment and ran the training command. The losses decreased normally, but the success rates are always 0.0%, whether on the kitchen_sdoor_open-v3 task or the pen-v0 task. I have tried my best to figure out this problem, but finally failed. Is this related to the recent updates to the mj_evns repository? Hope for help.

**Comment by suraj-nair-1** [comment]
Looking at the commits my guess is the env updates maybe impacted something in the visuals/physics, which would produce a distribution shift between the R3M demo data and evaluation env. But not sure yet, I'll take a closer look and try it out in a bit.

**Comment by suraj-nair-1** [comment]
Yeah I just confirmed, things were working fine for me on [this commit](https://github.com/vikashplus/mj_envs/commit/8c8b68c9a77981ca3bd3ff13f114f13a783ce2bf). When I re-cloned and installed the latest version of `stable` (and latest sub-modules), it no longer works and I indeed get the kitchen with completely different visuals. The demos are pre-collected so this will cause issues.

So I think reverting back to `8c8b68c9a77981ca3bd3ff13f114f13a783ce2bf` should resolve this.

**Comment by vikashplus** [comment]
@suraj-nair-1  -- both kitchen as well as the pen-v0 tasks?
Once I get a thumbs up, I'll merge `stable-bugtest` with `stable`.

**Comment by suraj-nair-1** [comment]
Just tested, I also get the expected performance for pen-v0. I think you should be good to merge.

**Comment by vikashplus** [comment]
Fixed in 8d125b5dbf48118cf34915ec2351608db469882b
