### ISSUE TITLE
Question about image sampling for r3m training.

### ISSUE THREAD

**Issue by jasonseu** [facebookresearch/r3m#19]
Hi, thanks for your impressive work. Recently I'm trying to retrain r3m model and confused about the sampling of images for contrastive learning. If I understand correctly, according to the code in `data_loaders.py`, taking `vidlen=30` and `alpha=0.2` as an example, then `start_in` is in `[1, 8]`, end_ind in `[23, 30]`, `s1_ind` in `[2, 30]`, `s0_ind` in `[1, s1_ind]` and `s2_ind` in `[s1_ind, 31]`.  Assuming that `start_in=7`, `end_ind=25`, `s1_ind=6`, `s0_ind=2` and `s2_ind=20`, then positive image-language pair of the second example in `trainer.py` is `{img7, img6, text}`, and one of the negative pair is `{img7, img2, text}`. I'm confused about this sampling result. In my opinion, transitioning from `img7` to `img2` completes the language `text` better than one from `img7` to `img6`, and the former should be positive example rather than negative example. Hope for help.

**Comment by suraj-nair-1** [comment]
Hi, the idea is that conditioned on some context initial frame, the score for satisfying the language should increase over the course of the video. The underlying assumption being that as you progress in the video, the better the language is satisfied (and an initial frame is needed for context as to where the video began).

Now depending on your choice of alpha, you may on rare occasion get an initial frame index that is after `s0_ind` and `s1_ind` as in the example you give above. Even in this case, I would still say the later frame should usually get a higher score, as the language instruction is likely better completed in a later frame than an earlier one. I don't quite follow why you think the earlier frame would complete the language better.

Regardless, a simple change to address this edge case is to choose a smaller alpha (`alpha=0` should only take the very first frame for `start_ind`), or you can sample `s1_ind` to be between `start_ind` and `end_ind`.
