### ISSUE TITLE
No "camera" with name left_cap2 exists. Available "camera" names = ('topview', 'corner', 'corner2', 'corner3', 'behindGripper', 'gripperPOV').

### ISSUE THREAD

**Issue by zhengsipeng** [facebookresearch/r3m#21]
Hi,
When I try to run the ""hammer-v2-goal-observable", "left cap2" on metaworld, it reporters the above error.
But the code runs well on "kitchen_sdoor_open-v3" with another environment.
Is there anything setting I miss or should I change some configs?

**Comment by suraj-nair-1** [comment]
Hi,
First, the camera options are different for the different domains.
Kitchen: "default","left_cap2","right_cap2"
MetaWorld: "left_cap2","right_cap2","top_cap2"
Adroit: "view_1","top","view_4"

Additionally, for MetaWorld make sure to use [the fork specified in the readme](https://github.com/suraj-nair-1/metaworld) to get the correct cameras.

**Comment by BetterZH** [comment]
> Hi, When I try to run the ""hammer-v2-goal-observable", "left cap2" on metaworld, it reporters the above error. But the code runs well on "kitchen_sdoor_open-v3" with another environment. Is there anything setting I miss or should I change some configs?

Hi！
I had the same problem. Have you solved it?

**Comment by suraj-nair-1** [comment]
Are you using the fork of Metaworld specified in the ReadMe?

**Comment by BetterZH** [comment]
> 

I used the command "`pip install git+https://github.com/rlworkgroup/metaworld.git@master#egg=metaworld`" in https://github.com/suraj-nair-1/metaworld  to install the MetaWorld. Is there anything setting I miss?

**Comment by suraj-nair-1** [comment]
Ah yeah thats the problem, that command will pull the version from rlworkgroup, not the fork. You need to clone the fork and install with `pip install -e .`

**Comment by BetterZH** [comment]
> Ah yeah thats the problem, that command will pull the version from rlworkgroup, not the fork. You need to clone the fork and install with `pip install -e .`

Thank you very much. The problem is solved.
