### ISSUE TITLE
Ego4D manifest/clip length

### ISSUE THREAD

**Issue by sanjayss34** [facebookresearch/r3m#23]
Hi, thanks for releasing your code! Would you be able to release the manifest file you used? In particular, the narrations file in the Ego4D data does not provide lengths for each of the fine-grained narrations. If you have any alternative recommendation for how to get the lengths, I'd appreciate that. Thanks!

**Comment by suraj-nair-1** [comment]
Hi, I think the solution most people have found to be effective is to extract clips manually. Please see the Issue here: https://github.com/facebookresearch/r3m/issues/13
