### ISSUE TITLE
Relation of frame indices

### ISSUE THREAD

**Issue by sanjayss34** [facebookresearch/r3m#24]
From the lines here https://github.com/facebookresearch/r3m/blob/b2334e726887fa0206962d7984c69c5fb09cceab/r3m/utils/data_loaders.py#L77 , it seems possible for frame `im0` to be after frames `imts0`/`imts1`/`imts2` (or some subset thereof). Is this not a problem for the loss terms where we want to train G(e_0, e_t, l) to be higher than G(e_0, e_<t, l) and G(e*_0, e*_<t, l)?

**Comment by suraj-nair-1** [comment]
Hi, thanks for the question. In short - yes it can on occasion happen but depending on the choice of alpha should be rare enough that it won't impact training. See this issue https://github.com/facebookresearch/r3m/issues/19 for a longer explanation.
