### ISSUE TITLE
Missing model.pt File

### ISSUE THREAD

**Issue by xiaoyue-H** [facebookresearch/r3m#35]
Recently I wanted to see the representation of R3M model. But it seems that the checkpoints file is missing.

FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/.r3m/r3m_50/model.pt'

How am I supposed to get to this file?

**Comment by wbjsamuel** [comment]
I solved this by manually downloading the ckpt from google drive with gdown. Hope this will work for you.

**Comment by xiaoyue-H** [comment]
got it, thank you.
