### ISSUE TITLE
Imitation Evaluation Code

### ISSUE THREAD

**Issue by Alxead** [facebookresearch/r3m#6]
Hi, thank you for releasing such a wonderful work. 
When the imitation learning evaluation code be released?

**Comment by suraj-nair-1** [comment]
Thank you! We hope to clean up and release the imitation code in 1-2 weeks. I'll close this issue once we release it.

**Comment by taokong** [comment]
also looking forward to the evaluation code

**Comment by MathisClautrier** [comment]
Hi, thank you for releasing your code, I would like to know if the imitation code will be released soon? Or if you could share the used demonstrations before it? thanks

**Comment by suraj-nair-1** [comment]
The evaluation code has been pushed to the `evaluation` folder in the new `eval` branch [here](https://github.com/facebookresearch/r3m/tree/eval/evaluation). While I'm still cleaning a few things up, it should contain everything needed to reproduce the experiments, and corresponding instructions. Please raise a new issue or email me if you have any questions.
