### ISSUE TITLE
Training process goes well, but evaluation results are either 0% or 100 % success rates.

### ISSUE THREAD

**Issue by jasonseu** [facebookresearch/r3m#8]
Hi, thanks for your awesome work. I follow the steps in README and successfully train the policy network. The loss decreases to a very low level. However, as shown in figure, the evaluation results show that max success rates are either 0% or 100% on benchmarks like kitchen_light_on-v3, kitchen_ldoor_open-v3 and kitchen_sdoor_open-v3. Is this reasonable? Or do you have any suggestions?

![image](https://user-images.githubusercontent.com/43087116/169545449-a855014a-7c13-4d68-af33-2b682066a80e.png)

**Comment by suraj-nair-1** [comment]
Hello,
Yeah this is not expected, while there can be variability between checkpoints only 0% or 100% is not what I observed.

First, could you share the exact command you are running? How many demos/what representation/etc. 

Also, you followed the installation setup instructions in the ReadMe [here](https://github.com/facebookresearch/r3m/tree/eval/evaluation), correct? Did you try the "Verifying Correct Installation" commands, and observe the expected numbers listed there (~60% for R3M and ~30% for CLIP)? If you are not getting those numbers then something likely is wrong in installation. For the Franka Kitchen did you make sure to add the line `FIXED_ENTRY_POINT = RANDOM_DESK_ENTRY_POINT`  in mj_envs to use the Randomized Desk?

**Comment by aravindr93** [comment]
Yes, this looks like an environment version mismatch issue. Please follow the Readme instructions exactly like Suraj mentioned to get the correct version of environments for evaluation.

**Comment by jasonseu** [comment]
Hi Suraj, thanks for your quick reply. I used the exact same commands as you suggested in the README for verifying correct installation. I follow your suggestions and add the line `FIXED_ENTRY_POINT = RANDOM_DESK_ENTRY_POINT` in mj_envs, and now that evaluation results look normal. Is it similar to the results of your experiment?

![image](https://user-images.githubusercontent.com/43087116/169700916-0f7187dc-d23a-4526-9942-5287e19a413f.png)

**Comment by suraj-nair-1** [comment]
Yup that looks right to me!
